WITH CTE AS (

    SELECT
        STARTED_AT AS STARTED_AT_RAW,
        TRY_TO_TIMESTAMP(STARTED_AT) AS STARTED_AT_TS,
        DATE(TRY_TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
        HOUR(TRY_TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
        CASE
            WHEN DAYNAME(TRY_TO_TIMESTAMP(STARTED_AT)) IN ('Sat', 'Sun')
                THEN 'WEEKEND'
            ELSE 'BUSINESSDAY'
        END AS DAY_TYPE
    FROM {{ source('demo', 'BIKE') }}

)

SELECT *
FROM CTE
